config/routes.rb
Rails.application.routes.draw do
  devise_for :moderators
  resources :moderators

  # root 'welcome#index'

end

app/models/moderator.rb
class Moderator < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # #
  # Validations
  #
  # validates :first_name, :last_name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/moderators_controller.rb
class ModeratorsController < ApplicationController
  before_action :set_moderator, only: [:show, :edit, :update, :destroy]

  # GET /moderators
  # GET /moderators.json
  def index
    @moderators = Moderator.all
  end

  # GET /moderators/1
  # GET /moderators/1.json
  def show
  end

  # GET /moderators/new
  def new
    @moderator = Moderator.new
  end

  # GET /moderators/1/edit
  def edit
  end

  # POST /moderators
  # POST /moderators.json
  def create
    @moderator = Moderator.new(moderator_params)

    respond_to do |format|
      if @moderator.save
        format.html { redirect_to @moderator, notice: 'Moderator was successfully created.' }
        format.json { render :show, status: :created, location: @moderator }
      else
        format.html { render :new }
        format.json { render json: @moderator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moderators/1
  # PATCH/PUT /moderators/1.json
  def update
    respond_to do |format|
      if @moderator.update(moderator_params)
        format.html { redirect_to @moderator, notice: 'Moderator was successfully updated.' }
        format.json { render :show, status: :ok, location: @moderator }
      else
        format.html { render :edit }
        format.json { render json: @moderator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moderators/1
  # DELETE /moderators/1.json
  def destroy
    @moderator.destroy
    respond_to do |format|
      format.html { redirect_to moderators_url, notice: 'Moderator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_moderator
      @moderator = Moderator.find(params[:id])
    end

    def moderator_params
      params.require(:moderator).permit(:first_name, :last_name, :email_address, :mission_id, :username, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AdoptAMissionary</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/moderators/_form.html.erb
<%= form_for(@moderator) do |f| %>
  <% if @moderator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@moderator.errors.count, "error") %> prohibited this moderator from being saved:</h2>

      <ul>
      <% @moderator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email_address %><br>
    <%= f.text_field :email_address %>
  </div>
  <div class="field">
    <%= f.label :mission_id %><br>
    <%= f.number_field :mission_id %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/moderators/edit.html.erb
<h1>Editing Moderator</h1>

<%= render 'form' %>

<%= link_to 'Show', @moderator %> |
<%= link_to 'Back', moderators_path %>

app/views/moderators/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Moderators</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email address</th>
      <th>Mission</th>
      <th>Username</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @moderators.each do |moderator| %>
      <tr>
        <td><%= moderator.first_name %></td>
        <td><%= moderator.last_name %></td>
        <td><%= moderator.email_address %></td>
        <td><%= moderator.mission_id %></td>
        <td><%= moderator.username %></td>
        <td><%= moderator.password %></td>
        <td><%= link_to 'Show', moderator %></td>
        <td><%= link_to 'Edit', edit_moderator_path(moderator) %></td>
        <td><%= link_to 'Destroy', moderator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Moderator', new_moderator_path %>

app/views/moderators/new.html.erb
<h1>New Moderator</h1>

<%= render 'form' %>

<%= link_to 'Back', moderators_path %>

app/views/moderators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @moderator.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @moderator.last_name %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @moderator.email_address %>
</p>

<p>
  <strong>Mission:</strong>
  <%= @moderator.mission_id %>
</p>

<p>
  <strong>Username:</strong>
  <%= @moderator.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @moderator.password %>
</p>

<%= link_to 'Edit', edit_moderator_path(@moderator) %> |
<%= link_to 'Back', moderators_path %>